RestRate/config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  
  resources :restrooms do
  	resources :reviews, except: [:index, :show]
  end 
 
  root 'restrooms#index'
  
  match '/about_us', to: 'pages#about_us', via: :get
  match '/contact_us', to: 'pages#contact_us', via: :get
end

RestRate/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

RestRate/app/models/building.rb
class Building < ActiveRecord::Base

		has_many :restrooms
end

RestRate/app/models/restroom.rb
class Restroom < ActiveRecord::Base
	has_many :reviews
	belongs_to :building
	validates_presence_of :name
	validates_presence_of :description
	validates_presence_of :city
	validates_presence_of :state
end

RestRate/app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :restroom
end

RestRate/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

RestRate/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

RestRate/app/controllers/buildings_controller.rb
class Buildings < Application Controller

end

RestRate/app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about_us
	end

	def contact_us
	end
end

RestRate/app/controllers/restrooms_controller.rb
class RestroomsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :new]
	def index
	end

	def new
		@restroom = Restroom.new
		#@restroom.save
	end

	def create 
		@restroom = Restroom.new(restroom_params)
		if	@restroom.save
		#redirect_to "/restrooms/show"
		#@restroom = Restroom.find{params[:id]}
			redirect_to @restroom
		else
			flash[:danger] = @restroom.errors.full_messages.to_sentence
			render 'new'
		end
	end

	def show
		@restroom = Restroom.find{params[:id]}
	end
	
	private 
		def restroom_params
			params.require(:restroom).permit(:name, :description, :address1, :address2, :building_id,
											 :city, :state, :zipcode, :phone, :email)
		end		
end

RestRate/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

end

RestRate/app/helpers/application_helper.rb
module ApplicationHelper
end

RestRate/app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

RestRate/app/views/layouts/_footer.html.erb
<!-- begin footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="span3">
                <div class="footer-widget">
                    <h2 class="brand widget-title">Realto</h2>
                    <p class="footer-tag-line">Your Company Tag Line</p>
                    <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                        magna aliqua adipisicing elit seddo eiusmod tempor.</p>
                </div>
                <!-- .footer-company-info -->
            </div>
            <!-- .span3 -->
            <div class="span3">
                <div class="footer-widget">
                    <h3 class="widget-title">Address</h3>
                    <div class="clearfix">
                        <ul>
                            <li class="clearfix">
                                <i class="icon-map-marker pull-left"></i>
                                <p class="pull-left">1680 Washington Avenue
                                    <br />Miami Beach 33139 FL</p></li>
                            <li class="clearfix">
                                <i class="icon-phone pull-left"></i>
                                <p class="pull-left">+1 (800) 765 4321</p></li>
                            <li class="clearfix">
                                <i class="icon-envelope-alt pull-left"></i>
                                <p class="pull-left"><a href="#">realto@realto.com</a></p>
                            </li>
                        </ul>
                    </div>
                    <!-- .clearfix -->
                </div>
                <!-- .footer-widget -->
            </div>
            <!-- .span3 -->
            <div class="span3">
                <div class="footer-widget">
                    <h3 class="widget-title">Company</h3>
                    <ul>
                        <li>
                            <i class="icon-caret-right"></i>
                            <a title="Home" href="#">Home</a></li>
                        <li>
                            <i class="icon-caret-right"></i>
                            <a title="About Us" href="#">About Us</a></li>
                        <li>
                            <i class="icon-caret-right"></i>
                            <a title="Properties" href="#">Properties</a></li>
                        <li>
                            <i class="icon-caret-right"></i>
                            <a title="Agents" href="#">Agents</a></li>
                        <li>
                            <i class="icon-caret-right"></i>
                            <a title="Blog" href="#">Blog</a></li>
                        <li>
                            <i class="icon-caret-right"></i>
                            <a title="Financing" href="#">Financing</a></li>
                        <li>
                            <i class="icon-caret-right"></i>
                            <a title="Contact Us" href="#">Contact Us</a></li>
                    </ul>
                </div>
                <!-- .footer-widget -->
            </div>
            <!-- .span3 -->
            <div class="span3">
                <div class="footer-widget">
                    <h3 class="widget-title">Flickr</h3>
                    <div class="flickr-widget">
                        <ul>
                          <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object"
                            src="http://placehold.it/70x70" /></a></li>
                            <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="http://placehold.it/70x70" /></a></li>
                            <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="http://placehold.it/70x70" /></a></li>
                            <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="http://placehold.it/70x70" /></a></li>
                            <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="http://placehold.it/70x70" /></a></li>
                            <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="http://placehold.it/70x70" /></a></li>
                            <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="http://placehold.it/70x70" /></a></li>
                        </ul>
                    </div>
                    <!-- .flickr-widget -->
                </div>
                <!-- .footer-widget -->
            </div>
            <!-- .span3 -->
        </div>
    </div>
</footer>

<!-- end footer -->

RestRate/app/views/layouts/_header.html.erb
<header>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="navbar-inner">
            <div class="container">
                <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        
                        <li>
                            <%= link_to root_path do%>
                            <i class="icon-home"></i>
                            <% end %>
                        </li>
                        <li><%= link_to "About Us", about_us_path%></li>
                        <li><%= link_to "Contact Us", contact_us_path%></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <div id="logo-container">
        <div class="container">
            <div class="row">
                <div class="span8">
                    <span class="logo-text">
                        <%= link_to "RestRate", root_path, class: "brand" %>    
                    </span>
                    <span class="tag-line hidden-phone">Weeding out the smelly</span>
                </div>
                <div class="span4">
                    <ul class="inline pull-right">
                        <li><%= link_to "Sign In", new_user_session_path %></li>
                        <li><%= link_to "Sign Up", new_user_registration_path %></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- #logo-container -->
</header>
<!-- end header -->

RestRate/app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

RestRate/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestRate</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body>
  <%= render 'layouts/header' %>

<div class="container">
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>
</div>

<%= yield %>
<% render 'layouts/footer' %>
</body>
</html>

RestRate/app/views/pages/about_us.html.erb
    <div class="container page-content">
      <div class="row">
        <div class="span12">
          <div class="box-container">
            <div class="padding30">
              <h2 class="page-title">About Us</h2>
              <p>Pellentesque habitant morbi tristique senectus et netus et malesuada
                fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
                ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
                egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend
                leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum
                erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean
                fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci,
                sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar
                facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor
                neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat
                volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis
                luctus, metus</p>
              <p>Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit
                amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros
                ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in
                turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus
                faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.
                Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor,
                facilisis luctus, metus</p>
              <p>Donec eu libero sit amet quam egestas semper. Aenean ultricies mi
                vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien
                ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo
                vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt
                condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
                Donec non enim in turpis pulvinar facilisis. Pellentesque habitant morbi
                tristique senectus et netus et malesuada fames ac turpis egestas.
                Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet,
                ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi
                vitae est. Mauris placerat eleifend leo.</p>
              <p>Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat
                wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean
                fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci,
                sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar
                facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor
                neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat
                volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis
                luctus, metus</p>
              <p>Pellentesque habitant morbi tristique senectus et netus et malesuada
                fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
                ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
                egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend
                leo.</p>
            </div>
          </div>
        </div>
        <!-- .span12 -->
      </div>
      <!-- .row -->
    </div>
    <!-- .container -->
    <div class="container">
      <div class="row">
        <div class="home-bottom-top">
          <div class="span4">
            <div class="info-box">
              <h2 class="secion-title">Why choose us?</h2>
              <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                magna aliqua adipisicing elit seddo eiusmod tempor.</p>
              <p>Sed perspiciatis unde omnisiste natus error voluptatem remopa
                accusantium doloremque laudantium, totam rem aperiam.</p>
              <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
            </div>
          </div>
          <!-- .span4 -->
          <div class="span4">
            <div class="info-box">
              <h3 class="info-head">Designed for your business</h3>
              <div class="row clearfix">
                <div class="pull-left icons hidden-phone">
                  <i class="icon-briefcase"></i>
                </div>
                <div class="span3">
                  <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                    magna aliqua adipisicing elit seddo eiusmod tempor.</p>
                  <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
                </div>
              </div>
              <!-- .clearfix -->
            </div>
            <!-- .info-box -->
            <div class="info-box">
              <h3 class="info-head">Ample Customizations</h3>
              <div class="row clearfix">
                <div class="pull-left icons hidden-phone">
                  <i class="icon-cogs"></i>
                </div>
                <div class="span3">
                  <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                    magna aliqua adipisicing elit seddo eiusmod tempor.</p>
                  <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
                </div>
              </div>
              <!-- .clearfix -->
            </div>
            <!-- .info-box -->
          </div>
          <!-- .span4 -->
          <div class="span4">
            <div class="info-box">
              <h3 class="info-head">Fully Responsive</h3>
              <div class="row clearfix">
                <div class="pull-left icons hidden-phone">
                  <i class="icon-move"></i>
                </div>
                <div class="span3">
                  <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                    magna aliqua adipisicing elit seddo eiusmod tempor.</p>
                  <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
                </div>
              </div>
              <!-- .clearfix -->
            </div>
            <!-- .info-box -->
            <div class="info-box">
              <h3 class="info-head">Bootstrap Compatible</h3>
              <div class="row clearfix">
                <div class="pull-left icons hidden-phone">
                  <i class="icon-thumbs-up"></i>
                </div>
                <div class="span3">
                  <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                    magna aliqua adipisicing elit seddo eiusmod tempor.</p>
                  <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
                </div>
              </div>
              <!-- .clearfix -->
            </div>
            <!-- .info-box -->
          </div>
          <!-- .span4 -->
        </div>
      </div>
    </div>

RestRate/app/views/pages/contact_us.html.erb
    <div class="container page-content">
      <div class="row">
        <div class="span8">
          <div class="box-container">
            <div class="padding30">
              <h2 class="page-title">Contact us</h2>
              <ul class="unstyled">
                <li>
                  <i class="icon-envelope-alt"></i>
                  Email: realto@realto.com</li>
                <li>
                  <i class="icon-phone"></i>
                  Phone: +1 786 345 6789</li>
                <li>
                  <i class="icon-linkedin"></i>
                  linkedin.com/realto</li>
                <li>
                  <i class="icon-twitter"></i>
                  twitter.com/realto</li>
              </ul>
              <div class="row-fluid">
                <form action="#" class="margin300" method="post" />
                  <input class="span6" placeholder="Please, insert your name" type="text" />
                  <input class="span6 pull-right" placeholder="Please, insert your email" type="text" />
                  <textarea class="span12" placeholder="Write your message" rows="6"></textarea>
                  <div class="clearfix">
                    <button class="btn btn-realto span6" type="submit">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- .span8 -->
        <div class="span4 widget">
          <div class="widget map box-container padding30">
            <h3 class="widget-title">Get Directions</h3>
            <iframe src="http://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=miami+beach+collins+ave+1220&amp;aq=&amp;sll=25.861386,-80.120888&amp;sspn=0.205136,0.347786&amp;ie=UTF8&amp;hq=&amp;hnear=1220+Collins+Ave,+Miami+Beach,+Miami-Dade,+Florida+33139,+Stati+Uniti&amp;t=m&amp;z=14&amp;ll=25.783255,-80.131265&amp;output=embed"></iframe>
            <dl class="margin0">
              <dt>Realto</dt>
              <dd class="margin0">1680 Washington Avenue</dd>
              <dd class="margin0">Miami Beach, FL 33139</dd>
            </dl>
          </div>
        </div>
        <!-- .span4 -->
      </div>
      <!-- .row -->
    </div>
    <!-- .container -->

RestRate/app/views/restrooms/new.html.erb
    <div class="container page-content">
      <div class="row">
        <div class="span8">
          <div class="box-container">
            <div class="padding30">
              <h2 class="page-title">Write a Review</h2>

             	<%= form_for @restroom do |f| %>
      					<%= f.label :name %> 
      					<%= f.text_field :name %>
      					<%= f.label :description %> 
      					<%= f.text_area :description %><br />
                <%= f.select :building_id, Building.all.map{ |f| [f.name, f.id] } %>
      					<%= f.label :address1 %> 
      					<%= f.text_field :address1 %>
      					<%= f.label :address2 %> 
      					<%= f.text_field :address2 %>
      					<%= f.label :city %> 
      					<%= f.text_field :city %>
      					<%= f.label :state %> 
      					<%= f.text_field :state %>
      					<%= f.label :zipcode %> 
      					<%= f.text_field :zipcode %>
      					<%= f.label :phone %> 
      					<%= f.text_field :phone %>
      					<%= f.label :email %> 
      					<%= f.text_field :email %><br />
      					<%= f.submit class: "btn span3 btn-realto-form btn-large"%>
			     	 <% end %> 

            </div>
          </div>
        </div>
        <!-- .span8 -->
        <div class="span4 widget">
          <div class="widget map box-container padding30">
            <h3 class="widget-title">Get Directions</h3>
            <iframe src="http://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=miami+beach+collins+ave+1220&amp;aq=&amp;sll=25.861386,-80.120888&amp;sspn=0.205136,0.347786&amp;ie=UTF8&amp;hq=&amp;hnear=1220+Collins+Ave,+Miami+Beach,+Miami-Dade,+Florida+33139,+Stati+Uniti&amp;t=m&amp;z=14&amp;ll=25.783255,-80.131265&amp;output=embed"></iframe>
            <dl class="margin0">
              <dt>Realto</dt>
              <dd class="margin0">1680 Washington Avenue</dd>
              <dd class="margin0">Miami Beach, FL 33139</dd>
            </dl>
          </div>
        </div>
        <!-- .span4 -->
      </div>
      <!-- .row -->
    </div>
    <!-- .container -->

RestRate/app/views/restrooms/show.html.erb
  <div class="container page-content">
      <div class="row">
        <div class="span8">
          <div class="box-container">
            <div class="cycle-slideshow" data-cycle-fx="fade" data-cycle-timeout="0" data-cycle-swipe="true" data-cycle-pager="#adv-custom-pager" data-cycle-pager-template='<a href="#" ><img src="{{src}}"></a>' data-cycle-prev="#prev" data-cycle-next="#next">
            
              <img alt="image" src="images/01.jpg" class="media-object" />
              
            </div><!-- .cycle-slideshow -->
            <div id="adv-custom-pager"></div>
            <div class="clearfix">
              <div class="clearfix padding30">
                <h2 clas="prop-title pull-left margin0">  <%= @restroom.name %> </h2>
                <span class="prop-price pull-right serif italic">****</span>
              </div>
              <div class="clearfix padding030 row-fluid">
                <ul class="more-info pull-left span6">
                  <li class="info-label clearfix"><span class="pull-left">Description: </span>
                    <span class="qty pull-right"> <%= @restroom.description %></span></li>
                  <li class="info-label clearfix"><span class="pull-left">Phone:</span>
                    <span class="qty pull-right"> <%= @restroom.phone %></span></li>
                  <li class="info-label clearfix"><span class="pull-left">Email:</span>
                    <span class="qty pull-right">  <%= @restroom.email %> </span></li>
                </ul>
                <ul class="more-info pull-right span6">
                  <li class="info-label clearfix"><span class="pull-left">Building:</span>
                    <span class="qty pull-right">  <%= @restroom.building.name %> </span></li>                 
                  <li class="info-label clearfix"><span class="pull-left">Address:</span>
                    <span class="qty pull-right">
                       <%= @restroom.address1 %><br />
                       <%= @restroom.address2 %><br />  
                       <%= @restroom.city %><br />
                       <%= @restroom.state %><br /> 
                       <%= @restroom.zipcode %><br />                     
                    </span>
                  </li>

                </ul>
              </div>
              <div class="clearfix padding30">
                <h3>Reviews</h3>
                <p>No reviews yet!</p>
              </div>
            </div>
          </div>
        </div>
        <!-- .span8 -->
        <div class="span4">
          <div class="widget map box-container padding30">
            <h3 class="widget-title">Map &amp; Directions</h3>
            <iframe src="http://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=miami+beach+collins+ave+1220&amp;aq=&amp;sll=25.861386,-80.120888&amp;sspn=0.205136,0.347786&amp;ie=UTF8&amp;hq=&amp;hnear=1220+Collins+Ave,+Miami+Beach,+Miami-Dade,+Florida+33139,+Stati+Uniti&amp;t=m&amp;z=14&amp;ll=25.783255,-80.131265&amp;output=embed"></iframe>
          </div>
          <div class="agent-box widget box-container clearfix padding30">
            <div class="">
              <div class="pull-left">
                <img alt="image" class="media-object agent-avatar" src="images/agent-01.jpg" />
              </div>
              <div class="pull-left">
                <h3>Contact Agent</h3>
                <ul>
                  <li>John Doe</li>
                  <li><a href="#">john.doe@realto.com</a></li>
                </ul>
              </div>
            </div>
          </div>
          <!-- .agent-box -->
          <div class="search-form widget">
            <p>Find your new home</p>
            <form action="#" class="row-fluid" method="post" />
              <select class="span12 select" name="type">
                <option />Location
                <option value="#" />New York
                <option value="#" />Los Angeles
                <option value="#" />Washington
                <option value="#" />Chicago
                <option value="#" />Miami
              </select>
              <select class="span12 select" name="type">
                <option />Property Type
                <option value="#" />Any
                <option value="#" />Single Family Home
                <option value="#" />Condo
                <option value="#" />Apartment
                <option value="#" />Loft
              </select>
              <select class="span6 select pull-left" name="beds">
                <option />Beds
                <option value="#" />1+ Beds
                <option value="#" />2+ Beds
                <option value="#" />3+ Beds
                <option value="#" />4+ Beds
                <option value="#" />5+ Beds
              </select>
              <select class="span6 select pull-right" name="baths">
                <option />Baths
                <option value="#" />1+ Baths
                <option value="#" />2+ Baths
                <option value="#" />3+ Baths
                <option value="#" />4+ Baths
                <option value="#" />5+ Baths
              </select>
              <select class="span12 select clearfix" name="status">
                <option />Select Status
                <option value="#" />For Rent
                <option value="#" />For Sale
              </select>
              <select class="span6 select pull-left" name="price-from">
                <option />Price from
                <option value="#" />from $100.000
                <option value="#" />from $200.000
                <option value="#" />from $300.000
                <option value="#" />from $400.000
                <option value="#" />from $500.000
              </select>
              <select class="span6 select pull-right" name="price-to">
                <option />Price to
                <option value="#" />to $100.000
                <option value="#" />to $200.000
                <option value="#" />to $300.000
                <option value="#" />to $400.000
                <option value="#" />to $500.000
              </select>
              <div class="clearfix">
                <button class="btn pull-right span6 btn-realto-form btn-large" type="submit">Search</button>
              </div>
            </form>
          </div>
          <!-- .search-form -->
        </div>
        <!-- .span4 -->
      </div>
      <!-- .row -->
    </div>
    <!-- .container -->
    <div class="container">
      <div class="row">
        <div class="span12 box-container">
          <div class="row adv-message clearfix">
            <div class="pull-left span7">
              <p class="upper-line serif italic">Realto xHTML/CSS Template is The
                Best Solution To Sell House Online</p>
              <p class="lower-line">This template is appropriate for Real Estate
                Company, who need to do their business online via websites.</p>
            </div>
            <!-- .pull-left -->
            <a class="pull-right btn btn-large btn-realto span3" href="#" title="Buy It Now">Buy
              It Now!</a>
          </div>
          <!-- .adv-message  -->
        </div>
      </div>
    </div>



    <!--      	 name, description, address1, address2, city, state, zipcode, phone, email		-->